### ISSUE TITLE
Feature Request: Resize based on window size

### ISSUE THREAD

**Issue by albertfilice** [Lodobo/rdict#3]
I'm trying to run in a terminal window with about ~50 characters wide and the output is much too wide for the terminal window. Is there a way to resize on the fly, or just with each output, based on the max width of the window?

**Comment by Lodobo** [comment]
Right now, the size is hard-coded, you could easily modify the source code to set the size you want and recompile.

The relevant file is `/src/rdict/search_word.rs`
You want to modify every occurance of the `wrap_text()` function and set a different `max_width` value.

The function definition is as follows:
`fn wrap_text(paragraph: &str, max_width: usize, indent_length: usize) -> String`

I'll look at how I can implement an automatic resize according to the terminal width. The `man` command does this, so I know it's possible and I know where to start.

**Comment by albertfilice** [comment]
Thanks! I managed to make the change on a fork of the repo, and then did the cargo install from the forked repo. Worked well, though I needed to tweak it a few times. Would be awesome if it scaled with window size, even just on the desktop would be nice. 
:)

**Comment by Lodobo** [comment]
@albertfilice It should work now. The line-width is set automatically according to the terminal-width. However, it is not dynamic. Which means if you resize the terminal after having run the command, it won't resize automatically.

**Comment by albertfilice** [comment]
Thank you!
